# -*- coding: utf-8 -*-
"""OctWave_Fraud_Detection (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ESYwj3Lj6FunTx0dWXL5SDsuh5s4sCh

# **OctWave 3.0 - Credit Card Fraud Detection Challenge**
### End-to-End Solution: **EDA** → **Feature Engineering** → **Model Comparison** → **Hyperparameter Tuning** → **Ensemble Check** → **Threshold Tuning** → **Final Submission**

**Author:** Yasandu Kethmika

**Evaluation Metric:** F1-score (fraud is rare, so precision/recall trade off matters more than raw accuracy)

**Approach summary:**
1. Explore the data and understand what actually separates fraud from legitimate transactions
2. Engineer a handful of domain informed features (night time flag, combined risk flag count, low device trust, high velocity)
3. Compare four models (Logistic Regression, Random Forest, XGBoost, LightGBM) with **stratified 5 fold cross validation**, not a single train/val split with only ~121 fraud rows in the whole training set, a single split is noisy and can be misleading
4. **Tune** the best model's hyperparameters with Optuna, searching directly against cross validated F1
5. **Check** (not assume) whether ensembling with a second model helps, using out of fold predictions
6. Tune the classification **threshold** using out of fold predictions, since F1 is threshold sensitive and the default 0.5 cutoff is rarely optimal for imbalanced problems
7. Run a leakage/robustness sanity check, then retrain on the full training set and generate the submission file
"""

!pip install -q gdown

import gdown

gdown.download(id="1yq591dczG3fnrctZsmC47jPYly3-JZ1j", output="train.csv", quiet=False)
gdown.download(id="1aAmADBqiO8pLFERkeFOM4gdxVSVmXzPQ", output="test.csv", quiet=False)
gdown.download(id="1LaKrbA4ejKEjVrv9aOK2vJU0dIcXRvgV", output="sample_submission.csv", quiet=False)

# ===== Imports =====
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    f1_score, precision_recall_curve, confusion_matrix,
    ConfusionMatrixDisplay, classification_report, roc_curve, auc
)

import xgboost as xgb
import lightgbm as lgb

import warnings
warnings.filterwarnings("ignore")

sns.set_style("whitegrid")
plt.rcParams["figure.dpi"] = 100

RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

"""## **1. Load the Data**"""

train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")
sample_submission = pd.read_csv("sample_submission.csv")

print("Train shape:", train.shape)
print("Test shape :", test.shape)
train.head()

# Basic sanity checks
print("Missing values in train:\n", train.isna().sum())
print("\nMissing values in test:\n", test.isna().sum())
print("\nDuplicate rows in train:", train.duplicated().sum())
print("Any transaction_id overlap between train/test:",
      len(set(train.transaction_id) & set(test.transaction_id)))
print("\nDtypes:\n", train.dtypes)

"""## **2. Exploratory Data Analysis**

### 2.1 Class Imbalance
This is the single most important fact about this dataset, fraud is rare. This is *why* the competition
uses F1-score instead of accuracy: a model that predicts "not fraud" for everything would still score ~98.5%
accuracy while being completely useless.
"""

fraud_counts = train["is_fraud"].value_counts()
fraud_pct = train["is_fraud"].value_counts(normalize=True) * 100

fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))

sns.countplot(x="is_fraud", data=train, palette=["#2E86AB", "#E63946"], ax=axes[0])
axes[0].set_title("Class Distribution (counts)")
axes[0].set_xticklabels(["Legitimate (0)", "Fraud (1)"])
for i, v in enumerate(fraud_counts.sort_index()):
    axes[0].text(i, v + 50, str(v), ha="center", fontweight="bold")

axes[1].pie(fraud_pct.sort_index(), labels=["Legitimate", "Fraud"],
            autopct="%1.2f%%", colors=["#2E86AB", "#E63946"], startangle=90)
axes[1].set_title("Class Distribution (%)")

plt.tight_layout()
plt.show()

print(f"Fraud rate: {fraud_pct[1]:.3f}%  ({fraud_counts[1]} fraud out of {len(train)} total)")

"""### **2.2 Numeric Feature Distributions by Class**
How does each numeric feature differ between legitimate and fraudulent transactions?
"""

numeric_cols = ["amount", "transaction_hour", "device_trust_score",
                 "velocity_last_24h", "cardholder_age"]

fig, axes = plt.subplots(2, 3, figsize=(16, 9))
axes = axes.flatten()

for i, col in enumerate(numeric_cols):
    sns.boxplot(x="is_fraud", y=col, data=train, palette=["#2E86AB", "#E63946"], ax=axes[i])
    axes[i].set_title(f"{col} by Class")
    axes[i].set_xticklabels(["Legit", "Fraud"])

axes[-1].axis("off")
plt.tight_layout()
plt.show()

"""### **2.3 Binary Risk Flags: `foreign_transaction` and `location_mismatch`**
These look like the strongest signals in the dataset; let's confirm.
"""

fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))

for i, col in enumerate(["foreign_transaction", "location_mismatch"]):
    rate = train.groupby(col)["is_fraud"].mean() * 100
    sns.barplot(x=rate.index, y=rate.values, palette=["#2E86AB", "#E63946"], ax=axes[i])
    axes[i].set_title(f"Fraud Rate by {col}")
    axes[i].set_ylabel("Fraud Rate (%)")
    axes[i].set_xlabel(col)
    for j, v in enumerate(rate.values):
        axes[i].text(j, v + 0.5, f"{v:.2f}%", ha="center", fontweight="bold")

plt.tight_layout()
plt.show()

"""### **2.4 Merchant Category vs Fraud Rate**"""

cat_rate = train.groupby("merchant_category")["is_fraud"].mean().sort_values(ascending=False) * 100

plt.figure(figsize=(8, 4.5))
sns.barplot(x=cat_rate.values, y=cat_rate.index, palette="Reds_r")
plt.xlabel("Fraud Rate (%)")
plt.title("Fraud Rate by Merchant Category")
for i, v in enumerate(cat_rate.values):
    plt.text(v + 0.05, i, f"{v:.2f}%", va="center", fontweight="bold")
plt.tight_layout()
plt.show()

"""### **2.5 Correlation Heatmap**"""

corr_cols = ["amount", "transaction_hour", "foreign_transaction", "location_mismatch",
             "device_trust_score", "velocity_last_24h", "cardholder_age", "is_fraud"]

plt.figure(figsize=(9, 7))
sns.heatmap(train[corr_cols].corr(), annot=True, fmt=".2f", cmap="coolwarm", center=0,
            linewidths=0.5)
plt.title("Correlation Matrix (incl. target)")
plt.tight_layout()
plt.show()

"""**EDA takeaways:**
- Fraud rate is **~1.5%** - strong class imbalance, F1/threshold tuning matters a lot
- `foreign_transaction=1` and `location_mismatch=1` transactions have **~8% fraud rate** vs <1% otherwise by far the strongest signals
- Fraud transactions happen disproportionately at **night** (low `transaction_hour`) and on devices with **low `device_trust_score`**
- `velocity_last_24h` is mildly elevated for fraud
- `amount`, `cardholder_age`, and `merchant_category` show weak/no relationship with fraud on their own

## **3. Feature Engineering**

Based on the EDA above, I engineer a few domain informed features on top of the raw ones:
- `is_night`: transaction happened between midnight and 5am (fraud is night-heavy)
- `risk_flag_sum`: sum of `foreign_transaction` + `location_mismatch` (0, 1, or 2 combined risk)
- `low_trust`: device trust score below 40 (fraud clusters at low trust)
- `high_velocity`: 4+ transactions in the last 24h
- `amount_log`: log-transform of amount to reduce skew
- One-hot encode `merchant_category`
"""

def engineer_features(df):
    df = df.copy()
    df["is_night"] = df["transaction_hour"].between(0, 5).astype(int)
    df["risk_flag_sum"] = df["foreign_transaction"] + df["location_mismatch"]
    df["low_trust"] = (df["device_trust_score"] < 40).astype(int)
    df["high_velocity"] = (df["velocity_last_24h"] >= 4).astype(int)
    df["amount_log"] = np.log1p(df["amount"])
    df = pd.get_dummies(df, columns=["merchant_category"], drop_first=True)
    return df

train_fe = engineer_features(train)
test_fe = engineer_features(test)

# Align test columns to train columns (in case a category is missing in test)
feature_cols = [c for c in train_fe.columns if c not in ["is_fraud", "transaction_id"]]
test_fe = test_fe.reindex(columns=feature_cols, fill_value=0)

X = train_fe[feature_cols]
y = train_fe["is_fraud"]
X_test_final = test_fe[feature_cols]

print("Feature columns:", feature_cols)
print("X shape:", X.shape, " | X_test shape:", X_test_final.shape)

"""## **4. Train / Validation Split**
Used for the confusion matrix / ROC visuals below. The final model (Section 6) is trained with proper
**stratified cross validation**, not this single split, since one split is noisy with only ~121 fraud rows total.
"""

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=RANDOM_STATE
)
print("Train:", X_train.shape, " Fraud rate:", y_train.mean().round(4))
print("Val  :", X_val.shape, " Fraud rate:", y_val.mean().round(4))

"""## **5. Model Comparison | Stratified 5-Fold Cross Validation**

I compare four models. For each fold, I find the **F1-optimal threshold** on the validation fold's
precision recall curve (rather than defaulting to 0.5), since that's what actually matters for
this competition's metric.
"""

def best_f1_and_threshold(y_true, proba):
    precision, recall, thresholds = precision_recall_curve(y_true, proba)
    f1_scores = 2 * precision * recall / (precision + recall + 1e-12)
    best_idx = np.argmax(f1_scores)
    best_thresh = thresholds[best_idx] if best_idx < len(thresholds) else 0.5
    return f1_scores[best_idx], best_thresh

def cross_val_f1(model_fn, X, y, n_splits=5, scale=False, set_spw=False):
    skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=RANDOM_STATE)
    fold_scores = []
    for tr_idx, val_idx in skf.split(X, y):
        Xtr, Xva = X.iloc[tr_idx], X.iloc[val_idx]
        ytr, yva = y.iloc[tr_idx], y.iloc[val_idx]

        if scale:
            scaler = StandardScaler()
            Xtr = scaler.fit_transform(Xtr)
            Xva = scaler.transform(Xva)

        model = model_fn(ytr) if set_spw else model_fn()
        model.fit(Xtr, ytr)
        proba = model.predict_proba(Xva)[:, 1]
        f1, _ = best_f1_and_threshold(yva, proba)
        fold_scores.append(f1)
    return fold_scores

results = {}

results["Logistic Regression"] = cross_val_f1(
    lambda: LogisticRegression(class_weight="balanced", max_iter=1000, random_state=RANDOM_STATE),
    X, y, scale=True
)

results["Random Forest"] = cross_val_f1(
    lambda: RandomForestClassifier(n_estimators=400, max_depth=8, class_weight="balanced",
                                    random_state=RANDOM_STATE, n_jobs=-1),
    X, y
)

results["XGBoost"] = cross_val_f1(
    lambda ytr: xgb.XGBClassifier(
        n_estimators=300, max_depth=4, learning_rate=0.05,
        eval_metric="logloss", random_state=RANDOM_STATE,
        scale_pos_weight=(ytr == 0).sum() / (ytr == 1).sum()
    ),
    X, y, set_spw=True
)

results["LightGBM"] = cross_val_f1(
    lambda: lgb.LGBMClassifier(n_estimators=300, max_depth=4, learning_rate=0.05,
                                class_weight="balanced", random_state=RANDOM_STATE, verbosity=-1),
    X, y
)

results_df = pd.DataFrame({m: {"mean_f1": np.mean(s), "std_f1": np.std(s)} for m, s in results.items()}).T
results_df = results_df.sort_values("mean_f1", ascending=False)
print(results_df)

fig, ax = plt.subplots(figsize=(9, 5))
means = [np.mean(results[m]) for m in results]
stds = [np.std(results[m]) for m in results]
colors = ["#E63946" if m == results_df.index[0] else "#2E86AB" for m in results]

bars = ax.bar(results.keys(), means, yerr=stds, capsize=6, color=colors)
ax.set_ylabel("Cross-Validated F1-score")
ax.set_title("Model Comparison — 5-Fold Stratified CV (F1-optimal threshold per fold)")
ax.set_ylim(0, 1.05)
for bar, m in zip(bars, means):
    ax.text(bar.get_x() + bar.get_width()/2, m + 0.02, f"{m:.3f}", ha="center", fontweight="bold")
plt.tight_layout()
plt.show()

print(f"\nBest model: {results_df.index[0]}  (mean CV F1 = {results_df.iloc[0]['mean_f1']:.4f})")

"""## **6. Final Model: Out of Fold Predictions & Threshold Tuning**

LightGBM comes out on top. To pick a threshold that will generalize (rather than one that overfits a
single validation fold), I generate **out-of-fold (OOF) predictions** across the full training set every row gets a prediction from a fold it was *not* trained on and tune the threshold on those.
"""

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)
oof_proba = np.zeros(len(X))

for tr_idx, val_idx in skf.split(X, y):
    Xtr, Xva = X.iloc[tr_idx], X.iloc[val_idx]
    ytr = y.iloc[tr_idx]
    model = lgb.LGBMClassifier(n_estimators=300, max_depth=4, learning_rate=0.05,
                                class_weight="balanced", random_state=RANDOM_STATE, verbosity=-1)
    model.fit(Xtr, ytr)
    oof_proba[val_idx] = model.predict_proba(Xva)[:, 1]

oof_f1, best_threshold = best_f1_and_threshold(y, oof_proba)
print(f"Out-of-fold F1: {oof_f1:.4f}")
print(f"Best threshold: {best_threshold:.4f}")

precision, recall, thresholds = precision_recall_curve(y, oof_proba)
f1_scores = 2 * precision * recall / (precision + recall + 1e-12)

fig, axes = plt.subplots(1, 2, figsize=(13, 5))

axes[0].plot(recall, precision, color="#E63946", linewidth=2)
axes[0].set_xlabel("Recall")
axes[0].set_ylabel("Precision")
axes[0].set_title("Precision-Recall Curve (Out-of-Fold)")
axes[0].grid(alpha=0.3)

axes[1].plot(thresholds, f1_scores[:-1], color="#2E86AB", linewidth=2)
axes[1].axvline(best_threshold, color="#E63946", linestyle="--",
                 label=f"Best threshold = {best_threshold:.3f}")
axes[1].set_xlabel("Decision Threshold")
axes[1].set_ylabel("F1-score")
axes[1].set_title("F1-score vs Threshold")
axes[1].legend()
axes[1].grid(alpha=0.3)

plt.tight_layout()
plt.show()

"""### **6.1 Confusion Matrix & Classification Report (at best threshold, OOF predictions)**"""

oof_pred = (oof_proba >= best_threshold).astype(int)

cm = confusion_matrix(y, oof_pred)
fig, ax = plt.subplots(figsize=(5.5, 5))
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["Legit", "Fraud"])
disp.plot(ax=ax, cmap="Blues", colorbar=False)
ax.set_title("Confusion Matrix (Out-of-Fold Predictions)")
plt.tight_layout()
plt.show()

print(classification_report(y, oof_pred, target_names=["Legit", "Fraud"], digits=4))

"""### **6.2 ROC Curve (Out-of-Fold)**"""

fpr, tpr, _ = roc_curve(y, oof_proba)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(6, 5))
plt.plot(fpr, tpr, color="#E63946", linewidth=2, label=f"ROC curve (AUC = {roc_auc:.4f})")
plt.plot([0, 1], [0, 1], linestyle="--", color="gray")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve — LightGBM (Out-of-Fold)")
plt.legend(loc="lower right")
plt.tight_layout()
plt.show()

"""## **6.3 Hyperparameter Tuning (Optuna)**

The Section 5/6 models above use reasonable default ish parameters, not tuned ones. Here I use
[Optuna](https://optuna.org/) to search LightGBM's hyperparameter space directly against the metric
that matters  **cross-validated F1** , rather than logloss or accuracy. Each trial runs a full
stratified 5 fold CV so the search doesn't overfit to a single split.
"""

!pip install -q optuna

import optuna
optuna.logging.set_verbosity(optuna.logging.WARNING)

def optuna_objective(trial):
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 150, 500),
        "max_depth": trial.suggest_int("max_depth", 3, 8),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.15, log=True),
        "num_leaves": trial.suggest_int("num_leaves", 15, 63),
        "min_child_samples": trial.suggest_int("min_child_samples", 5, 40),
        "subsample": trial.suggest_float("subsample", 0.6, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),
        "class_weight": "balanced",
        "random_state": RANDOM_STATE,
        "verbosity": -1,
    }
    skf_tune = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)
    fold_f1s = []
    for tr_idx, val_idx in skf_tune.split(X, y):
        Xtr, Xva = X.iloc[tr_idx], X.iloc[val_idx]
        ytr, yva = y.iloc[tr_idx], y.iloc[val_idx]
        m = lgb.LGBMClassifier(**params)
        m.fit(Xtr, ytr)
        proba = m.predict_proba(Xva)[:, 1]
        f1, _ = best_f1_and_threshold(yva, proba)
        fold_f1s.append(f1)
    return np.mean(fold_f1s)

study = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE))
study.optimize(optuna_objective, n_trials=40, show_progress_bar=False)

best_lgb_params = study.best_params
best_lgb_params.update({"class_weight": "balanced", "random_state": RANDOM_STATE, "verbosity": -1})

print(f"Baseline LightGBM CV F1 (Section 5): {np.mean(results['LightGBM']):.4f}")
print(f"Tuned LightGBM CV F1 (Optuna, {len(study.trials)} trials): {study.best_value:.4f}")
print("\nBest hyperparameters found:")
for k, v in best_lgb_params.items():
    print(f"  {k}: {v}")

"""## **6.4 Ensemble Check: Tuned LightGBM + XGBoost**

Before committing to a final model, I check whether blending the tuned LightGBM with XGBoost actually
improves things, using out-of-fold predictions for both. **This is a genuine check, not a foregone
conclusion** ensembling doesn't always help, especially when one model is already strong and the
second is meaningfully weaker; in that case the weaker model's errors don't cancel out, they just
dilute the stronger model's correct calls.
"""

skf_final = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)
oof_lgb_tuned = np.zeros(len(X))
oof_xgb_check = np.zeros(len(X))

for tr_idx, val_idx in skf_final.split(X, y):
    Xtr, Xva = X.iloc[tr_idx], X.iloc[val_idx]
    ytr, yva = y.iloc[tr_idx], y.iloc[val_idx]

    m_lgb = lgb.LGBMClassifier(**best_lgb_params)
    m_lgb.fit(Xtr, ytr)
    oof_lgb_tuned[val_idx] = m_lgb.predict_proba(Xva)[:, 1]

    spw = (ytr == 0).sum() / (ytr == 1).sum()
    m_xgb = xgb.XGBClassifier(n_estimators=300, max_depth=4, learning_rate=0.05,
                               eval_metric="logloss", random_state=RANDOM_STATE, scale_pos_weight=spw)
    m_xgb.fit(Xtr, ytr)
    oof_xgb_check[val_idx] = m_xgb.predict_proba(Xva)[:, 1]

f1_lgb_tuned, _ = best_f1_and_threshold(y, oof_lgb_tuned)
f1_xgb_check, _ = best_f1_and_threshold(y, oof_xgb_check)

print(f"Tuned LightGBM alone — OOF F1: {f1_lgb_tuned:.4f}")
print(f"XGBoost alone         — OOF F1: {f1_xgb_check:.4f}")
print()

# Try blending at several weights to see if ANY blend beats tuned LightGBM alone
blend_results = []
for w in [0.5, 0.6, 0.7, 0.8, 0.9, 1.0]:
    blend = w * oof_lgb_tuned + (1 - w) * oof_xgb_check
    f1_blend, _ = best_f1_and_threshold(y, blend)
    blend_results.append((w, f1_blend))
    print(f"  Blend weight (LightGBM={w:.1f} / XGBoost={1-w:.1f}): OOF F1 = {f1_blend:.4f}")

best_blend_w, best_blend_f1 = max(blend_results, key=lambda x: x[1])

if best_blend_f1 > f1_lgb_tuned + 1e-6:
    print(f"\n-> Ensembling helps: best blend (w={best_blend_w}) beats tuned LightGBM alone.")
    USE_ENSEMBLE = True
else:
    print("\n-> Ensembling does NOT beat tuned LightGBM alone on this data.")
    print("   XGBoost's OOF F1 is noticeably lower, so blending only dilutes the stronger model.")
    print("   Decision: use tuned LightGBM alone as the final model.")
    USE_ENSEMBLE = False

"""## **6.5 Leakage & Robustness Sanity Check**

A 0.99+ F1 is unusually high, so before trusting it I check for the usual causes of an
artificially inflated score.
"""

print("1. Is transaction_id used as a feature?", "transaction_id" in X.columns, "(should be False)")
print()

print("2. Per-fold F1 for the tuned model (checking no single fold is propping up the average):")
skf_check = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)
per_fold_f1 = []
for i, (tr_idx, val_idx) in enumerate(skf_check.split(X, y)):
    Xtr, Xva = X.iloc[tr_idx], X.iloc[val_idx]
    ytr, yva = y.iloc[tr_idx], y.iloc[val_idx]
    m = lgb.LGBMClassifier(**best_lgb_params)
    m.fit(Xtr, ytr)
    proba = m.predict_proba(Xva)[:, 1]
    f1, _ = best_f1_and_threshold(yva, proba)
    per_fold_f1.append(f1)
    print(f"   Fold {i+1}: F1 = {f1:.4f}  (n_fraud_in_fold = {yva.sum()})")
print(f"   Mean: {np.mean(per_fold_f1):.4f}  |  Std: {np.std(per_fold_f1):.4f}")
print()

print("3. Train vs test feature distributions (should look similar — no obvious drift):")
compare_cols = ["amount", "transaction_hour", "device_trust_score", "velocity_last_24h", "cardholder_age"]
comparison = pd.DataFrame({
    "train_mean": train[compare_cols].mean(),
    "test_mean": test[compare_cols].mean(),
    "train_std": train[compare_cols].std(),
    "test_std": test[compare_cols].std(),
})
print(comparison)
print()
print("Conclusion: no ID leakage, no single fold dominating, train/test distributions are consistent.")
print("The high F1 reflects that foreign_transaction + location_mismatch + device_trust_score genuinely")
print("separate fraud very well in this dataset — it is not an artifact of a bug.")

"""## **7. Feature Importance**
Trained on the full training set, to see which features the final model relies on most.
"""

final_model = lgb.LGBMClassifier(**best_lgb_params)
final_model.fit(X, y)

importance_df = pd.DataFrame({
    "feature": X.columns,
    "importance": final_model.feature_importances_
}).sort_values("importance", ascending=False)

plt.figure(figsize=(9, 6))
sns.barplot(x="importance", y="feature", data=importance_df, palette="viridis")
plt.title("LightGBM Feature Importance (Final Model, Full Training Data)")
plt.tight_layout()
plt.show()

importance_df

"""## **8. Generate Final Predictions on Test Set**

The final model was already trained on the **full** training set in Section 7 (`final_model`, using the
Optuna tuned hyperparameters). I re derive the F1-optimal threshold from the *tuned* model's out-of-fold
predictions (Section 6.4's `oof_lgb_tuned`), this supersedes the baseline threshold from Section 6, since
the model itself changed.
"""

final_threshold, _ = None, None  # placeholder overwritten below
f1_final_oof, final_threshold = best_f1_and_threshold(y, oof_lgb_tuned)
print(f"Final tuned-model OOF F1: {f1_final_oof:.4f}")
print(f"Final decision threshold: {final_threshold:.4f}")

test_proba = final_model.predict_proba(X_test_final)[:, 1]
test_pred = (test_proba >= final_threshold).astype(int)

submission = pd.DataFrame({
    "transaction_id": test["transaction_id"],
    "is_fraud": test_pred
})

# Sanity checks before saving
assert submission.shape[0] == sample_submission.shape[0], "Row count mismatch with sample_submission!"
assert set(submission["transaction_id"]) == set(sample_submission["transaction_id"]), "ID mismatch!"
assert set(submission["is_fraud"].unique()).issubset({0, 1}), "Non-binary predictions!"

print("Predicted fraud rate on test set:", submission["is_fraud"].mean().round(4))
print("Predicted fraud count:", submission["is_fraud"].sum(), "out of", len(submission))

submission.to_csv("submission.csv", index=False)
submission.head()

"""## **9. Methodology Summary (for competition writeup)**

**Data:** 8,000 training transactions, 9 raw features, 1.51% fraud rate.

**Preprocessing / Feature Engineering:** No missing values or duplicates. Added 5 engineered features
(`is_night`, `risk_flag_sum`, `low_trust`, `high_velocity`, `amount_log`) derived from EDA observed patterns,
plus one hot encoded `merchant_category`.

**Class Imbalance Handling:** Used `class_weight="balanced"` (LightGBM/Random Forest/Logistic Regression)
or `scale_pos_weight` (XGBoost) rather than oversampling (e.g. SMOTE), since tree based models with class
weighting handle this rare event imbalance well without risking synthetic sample artifacts.

**Model Selection:** Compared Logistic Regression, Random Forest, XGBoost, and LightGBM using stratified
5 fold cross validation (critical here only ~121 fraud rows total, so a single split is unreliable).
LightGBM had the highest and most consistent cross validated F1.

**Hyperparameter Tuning:** Used Optuna to search LightGBM's hyperparameter space (tree depth, learning
rate, leaf count, subsampling) directly against cross validated F1, rather than relying on default settings.

**Ensembling  tested, not assumed:**
Checked whether blending the tuned LightGBM with XGBoost improved
out-of-fold F1 at several blend weights. It did not XGBoost's OOF F1 was consistently lower, so blending
only diluted the stronger model. The tuned LightGBM was kept as a standalone final model rather than
force fitting an ensemble that didn't earn its place.

**Threshold Tuning:** Rather than using the default 0.5 cutoff, I generated out-of-fold predictions across
the entire training set and selected the threshold that maximizes F1 on the precision-recall curve. This
was re-derived after tuning, since the threshold that fits the untuned model isn't necessarily optimal for
the tuned one.

**Leakage / Robustness Check:** Confirmed `transaction_id` was never used as a feature, checked per-fold F1
for any single fold inflating the average, and compared train/test feature distributions for drift - no
red flags found. *italicized text*

**Final Model:** Optuna tuned LightGBM retrained on the full training set, using the re derived OOF tuned
threshold to convert probabilities to binary predictions on the test set.

**Reproducibility:** All randomness is seeded (`RANDOM_STATE = 42`) for reproducible results.

"""